name: sync

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: get LuaJIT
        run: |
          git clone -single-branch --depth=1 https://github.com/LuaJIT/LuaJIT.git

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: sync docs
        run: |
          rm -rf docs
          mv ../LuaJIT/doc docs
          mv docs/luajit.html docs/index.html
          git add -A
          git commit -m 'update'
          git push
