name: sync-docs

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: get LuaJIT
        run: |
          git clone --single-branch --depth=1 https://github.com/LuaJIT/LuaJIT.git
          mv LuaJIT /tmp

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: sync docs
        run: |
          rm -rf docs
          mv /tmp/LuaJIT/doc docs
          mv docs/luajit.html docs/index.html
          echo "luajit.lubinlew.com" > docs/CNAME
          git config --global user.email "lgbxyz@gmail.com"
          git config --global user.name "LubinLew"
          git add -A
          git commit -m 'update'
          git push
